### ISSUE TITLE
Chrome 28.0.1500.95 shows wrong point

### ISSUE THREAD

**Issue by lacivert** [ericdrowell/MeteorCharts#1]
![screen shot 2013-08-24 at 15 45 57 pm](https://f.cloud.github.com/assets/945612/1020702/815b577e-0cbb-11e3-9053-da70188e6e59.png)

You see, blue point should have been upper than now it points.
I am using mac os x 10.8.4, chrome 28.0.1500.95

**Comment by lacivert** [comment]
Updated to 29.0.1547.57, still issue happens.

**Comment by ericdrowell** [comment]
Sorry for the headache!  This is actually an issue with pixel ratio with KineticJS, the rendering engine for MeteorCharts.  It'l be fixed soon.

What kind of Apple device are you using?  iMac? Pro?

**Comment by lacivert** [comment]
Pro with Retina. If it is about pixel ratio, then it may be a problem of Retina display.
On the other hand, it works fine on Safari

**Comment by ericdrowell** [comment]
Yes, it's a device pixel ratio with the clipping region around the data.  This is a bug in KineticJS which was just resolved.  The next version of KineticJS (4.6.1) will fix up the problem.  In the mean time, I'll go ahead and upload a beta version of Kinetic to patch the issue for the time being.  Thank you!
